package main.java.model;

import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.List;

public class Report {

    private int id;
    private String generatedBy;
    private String project;
    private List<String> bugsSummaries;
    private LocalDateTime generatedDate;

    public Report() {}

    public Report(int id, String generatedBy, String project,
                  List<String> bugsSummaries, LocalDateTime generatedDate) {
        this.id = id;
        this.generatedBy = generatedBy;
        this.project = project;
        this.bugsSummaries = bugsSummaries;
        this.generatedDate = generatedDate;
    }

    // Getters
    public int getter_id()                        { return id; }
    public String getter_generatedBy()            { return generatedBy; }
    public String getter_project()                { return project; }
    public List<String> getter_bugs_summaries()   { return bugsSummaries; }
    public LocalDateTime getter_generatedDate()   { return generatedDate; }

    // Setters
    public void setter_id(int id)                                  { this.id = id; }
    public void setter_generatedBy(String generatedBy)             { this.generatedBy = generatedBy; }
    public void setter_project(String project)                     { this.project = project; }
    public void setter_bugs_summaries(List<String> bugsSummaries)  { this.bugsSummaries = bugsSummaries; }
    public void setter_generatedDate(LocalDateTime generatedDate)  { this.generatedDate = generatedDate; }

    public String generateFormattedReport() {
        DateTimeFormatter fmt = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm");
        StringBuilder sb = new StringBuilder();
        sb.append("=== Project Report ===\n");
        sb.append("Project: ").append(project).append("\n");
        sb.append("Generated By: ").append(generatedBy).append("\n");
        sb.append("Date: ").append(generatedDate.format(fmt)).append("\n\n");
        sb.append("Bug Summaries:\n");
        if (bugsSummaries != null) {
            for (String bug : bugsSummaries) {
                sb.append("  - ").append(bug).append("\n");
            }
        }
        return sb.toString();
    }
}
